### ISSUE TITLE
请教下...

### ISSUE THREAD

**Issue by ylmyg** [SilenceDut/diffadapter#1]
作者你好，我项目中已经使用了你的TaskScheduler和Router，现在想学习组件化的开发，但是知天气已经获取不到天气数据了，diffadapter用的是kotlin开发，请问下diffadapter非Kotlin开发的是哪个版本？

**Comment by SilenceDut** [comment]
diffadapter的库是java实现的，但是demo是kotlin，但是语言不影响看框架的，代码量也不大，你可以看懂的，别怕😁

**Comment by ylmyg** [comment]
想请假下，学习kotlin难度大么？目前我认为学习kotlin还不如学习Flutter。呵呵。不知作者学习了Flutter了么
